### ISSUE TITLE
FAILED LIBRARY JAR: Could not normalize path

### ISSUE THREAD

**Issue by angelilu2599** [Arrowgene/net.arrowgene.dance#1]
I was trying to gradle install this server emulator. Not for _DANCE! Online_ but for a game that I think is similar in the aspect of server-client communication. I'm learning to revive it (personally). The Vietnamese version is already gone off. But the Chinese version is still living. Game link: http://mf.818long.com/

However, I have been continuously meeting this error. (screencap)
I'm new to Java (I try learning all things for the revival), so don't blame me for my keep being stuck at this error.

I guess maybe the problem is that path is actually concatenated from more paths?
How could I navigate the error(s) (if is) in the source code, so as to fix it? 

Thank you very much in advance.

![image](https://user-images.githubusercontent.com/85763245/121736468-ce463900-cb21-11eb-9337-ce5185645239.png)

**Comment by sebastian-heinz** [comment]
I have not encountered this error yet. It looks like gradle has trouble making the correct path. Could you try `gradlew build`? Perhaps it is related to the gradle version
